name: flutter_responsive_flex_grid
description: Quickly Build responsive flutter application with FlutterResponsiveFlexGrid. Create Responsive Grid for multiple screen sizes in Flutter.
version: 0.0.1
homepage: https://github.com/CelestialSystem/FlutterResponsiveFlexGrid

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
